name: 'Minecraft AFKBot'
author: 'Minionguyjpro'
branding:
  icon: 'box'
  color: 'blue'
description: 'An Minecraft NodeJS bot to stay afk in servers.'

inputs:
  bot-enabled:
    description: 'Enable the bot.'
    required: false
    default: ''
    
runs:
 using: 'node12'
 main: 'index.js'


