name: Test

on:
  push:
  pull_request:

jobs:
 build:
    runs-on: windows-latest
    steps:
     - uses: actions/checkout@v2
     - name: Create report file
       run: date +%s > report.txt  

     
     - name: Minecraft AFKBot
       uses: Minionguyjpro/Afk-bot@v1.0.2_beta
       with:
        ip: Minionguyjpro.aternos.me
        name: AFK
        port: 53166
